# Generated by Django 4.1.7 on 2023-03-26 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datamcu',
            name='wind_speed',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='datamcu',
            name='soil_moisture',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='datamcu',
            name='soil_temp',
            field=models.FloatField(default=0),
        ),
    ]
