# Generated by Django 4.1.7 on 2023-03-27 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='profile',
            table='profile',
        ),
    ]
