# Generated by Django 4.1.7 on 2023-03-27 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_rename_profile_customer_alter_customer_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={},
        ),
        migrations.AlterModelTable(
            name='customer',
            table=None,
        ),
    ]
